project_id = "lkgvewhoqmieklsqxgjn"

[functions.notify-offer-accepted]
verify_jwt = false

[functions.notify-new-offer]
verify_jwt = false

[functions.notify-motoboy-arrived]
verify_jwt = false

[functions.notify-snack-exchange]
verify_jwt = false

[functions.notify-rating-reminder]
verify_jwt = false

[functions.check-pending-ratings]
verify_jwt = false

[functions.motoboy-assistant]
verify_jwt = false

[functions.notify-ranking-change]
verify_jwt = false

[functions.notify-account-activated]
verify_jwt = false

[functions.notify-offer-cancelled]
verify_jwt = false
