project_id = "lkgvewhoqmieklsqxgjn"

[functions.notify-offer-accepted]
verify_jwt = false

[functions.notify-new-offer]
verify_jwt = false

[functions.notify-motoboy-arrived]
verify_jwt = false

[functions.notify-snack-exchange]
verify_jwt = false

[functions.notify-rating-reminder]
verify_jwt = false
